FROM golang:1.18.2

WORKDIR /app

COPY go.* ./
RUN go mod download

COPY ./Lesson_20-final-project/1-Gateway/ ./Lesson_20-final-project/1-Gateway/ 

RUN go build -o /Gateway ./Lesson_20-final-project/1-Gateway/cmd/main.go

CMD [ "/Gateway" ]