FROM golang:1.18.2

WORKDIR /app

COPY go.* ./
RUN go mod download

COPY ./Lesson_20-final-project/2-Shortener/ ./Lesson_20-final-project/2-Shortener/ 

RUN go build -o /Shortener ./Lesson_20-final-project/2-Shortener/cmd/main.go

CMD [ "/Shortener" ]