FROM golang:1.18.2

WORKDIR /app

COPY go.* ./
RUN go mod download

COPY ./Lesson_20-final-project/4-Analytics/ ./Lesson_20-final-project/4-Analytics/ 

RUN go build -o /Analytics ./Lesson_20-final-project/4-Analytics/cmd/analytics/main.go

CMD [ "/Analytics" ]