version: "3"
services:
  gw:
    build:
      context: .
      dockerfile: ./Dockerfile.gw
    environment:
      SHORTNER_NEW_URL: "http://shortener:8080/api/v1/url"
      SHORTNER_URL: "http://shortener:8080/api/v1/urls"
      CACHE_URL: "http://cache:8082/api/v1/urls"
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
    restart: always
  shortener:
    build:
      context: .
      dockerfile: ./Dockerfile.shortener
    environment:
      QUEUE_CONN: "amqp://guest:guest@rabbitmq:5672/"
      MONGO_CONN: "mongodb://shortener-mongo:27017/"
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
    restart: always
  cache:
    build:
      context: .
      dockerfile: ./Dockerfile.cache
    environment:
      QUEUE_CONN: "amqp://guest:guest@rabbitmq:5672/"
      REDIS_ADDR: "redis:6379"
    ports:
      - 8082:8082
    depends_on:
      - rabbitmq
    restart: always
  analytics:
    build:
      context: .
      dockerfile: ./Dockerfile.analytics
    environment:
      QUEUE_CONN: "amqp://guest:guest@rabbitmq:5672/"
    ports:
      - 8081:8081
    depends_on:
      - rabbitmq
    restart: always
  shortener-mongo:
    image: mongo:latest
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:3.10-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 50
  redis:
    image: redis:latest
    ports:
      - 6380:6379

volumes:
  mongo:


