# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("messages.proto", :syntax => :proto3) do
    add_message "protobuf.Message" do
      optional :id, :int64, 1
      optional :created_at, :message, 2, "google.protobuf.Timestamp"
      optional :text, :string, 3
    end
    add_message "protobuf.Empty" do
    end
  end
end

module Protobuf
  Message = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf.Message").msgclass
  Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf.Empty").msgclass
end
