# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: messages.proto for package 'protobuf'

require 'grpc'
require 'messages_pb'

module Protobuf
  module Signalman
    # Описание службы gRPC.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'protobuf.Signalman'

      rpc :Messages, ::Protobuf::Empty, stream(::Protobuf::Message)
      rpc :Send, ::Protobuf::Message, ::Protobuf::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
